package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	graphql_gen "github.com/yeencloud/svc-gateway/contract/graphql/generated"
)

// Empty is the resolver for the _empty field.
func (r *mutationResolver) Empty(ctx context.Context) (*string, error) {
	panic(fmt.Errorf("not implemented: Empty - _empty"))
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Mutation returns graphql_gen.MutationResolver implementation.
func (r *Resolver) Mutation() graphql_gen.MutationResolver { return &mutationResolver{r} }

// Query returns graphql_gen.QueryResolver implementation.
func (r *Resolver) Query() graphql_gen.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
