package graphql

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.85

import (
	"context"
	"fmt"

	"github.com/samber/lo"
	"github.com/yeencloud/svc-gateway/contract/graphql/generated"
)

// UpdateProfile is the resolver for the updateProfile field.
func (r *mutationResolver) UpdateProfile(ctx context.Context, input generated.UpdateProfileInput) (*generated.Profile, error) {
	panic(fmt.Errorf("not implemented: UpdateProfile - updateProfile"))
}

// Profile is the resolver for the profile field.
func (r *queryResolver) Profile(ctx context.Context, id string) (*generated.Profile, error) {
	return &generated.Profile{
		ID:  id,
		Bio: lo.ToPtr("Jeanine"),
	}, nil
}
