// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type CreateUserInput struct {
	Name string `json:"name"`
}

type Mutation struct {
}

type Profile struct {
	ID  string  `json:"id"`
	Bio *string `json:"bio,omitempty"`
}

type Query struct {
}

type UpdateProfileInput struct {
	ID  string  `json:"id"`
	Bio *string `json:"bio,omitempty"`
}

type User struct {
	ID      string   `json:"id"`
	Name    string   `json:"name"`
	Profile *Profile `json:"profile,omitempty"`
}
